### ISSUE TITLE
prepare the get-ready installation manual 

### ISSUE THREAD

**Issue by SaraMati** [BME1478H/BME1478material#5]
make a document helping students installing bash and python for different operating systems (and IDE of choice?) before start of the lectures

**Comment by linamnt** [comment]
I really like the Carpentries instructions for set-up of Git/Bash/Text Editor/Python. It has very thorough step-by-step guides for Mac/Linux/Windows. 

See the bottom of the Carpentries workshop:
http://carpentries.github.io/workshop-template/

**Should we just direct students to this documentation?** 
It confirms all students will have the same versions UNLESS they specify otherwise (because they already use bash/python etc)

**Confirming pre-install before class**
We can ask students to send a confirmation in the pre-course survey about whether they have all of Bash, Git, Python3/Anaconda, and Nano (and or text editor of their choice) and if not, maybe they will have to come early/drop by office hours to get everything installed by the end of the first week?

**Comment by joelostblom** [comment]
👍 I think it's worthwhile having all students install anaconda even if they already have python from another source once previously. It makes supporting them much easier.

The SC instructions look good to me, note that anaconda no longer recommend prepending to path (at least not for LINUX, and I think also not for Mac), and uses `conda init` automatically (or maybe asks) during installation instead. This is a lesser point since most people will use windows, but might be worthwhile running through an up to date installation on each OS. 

Since there is a lot of additional info on that SC page, maybe we can copy just the relevant sections to a file in this repo and link that? If we want to add python package installation instructions, feel free to take them (and anything else) from the workshop notebooks https://github.com/UofTCoders/workshops-dc-py/blob/master/notebooks/rmd/1-programmatic-data-analyses.Rmd#L751-L775.

**Comment by linamnt** [comment]
Yes sounds good, I can make a file with those instructions + some updates (e.g. not preprending path, installing package etc)
